################################################################################
#                          Covariate plots versus ηs                           #
################################################################################
"""
    etacov(
        res::PumasModel;
        cvs = [],
        continuoustype = :scatter,
        discretetype = :boxplot,
        catmap = NamedTuple()
    )

Plots the covariates of the model (defaults to all, can be specified by `cvs`)
against the `η`s (also called the `ebe`s).

It works differently for categorical and continuous covariates.  For categorical
covariates, a box plot will be generated by default
(configurable by `discretetype`);
for continuous covariates, a scatter plot will be generated
(configurable by `continuoustype`).

Whether an array is categorical or not is determined by the function [`iscategorical`](@ref),
but you can override this automated heuristic by providing a `NamedTuple` of the
form `(colname = true)` to set colname to be treated as categorical, or `false`
for it to be treated as continuous.
"""
@userplot EtaCov

@recipe function f(
            ec::EtaCov;
            cvs = [],
            continuoustype = :scatter,
            discretetype = :boxplot,
            catmap = NamedTuple()
        )

    @show typeof(ec)

    @assert length(ec.args) == 1
    @assert eltype(ec.args) <: Union{PumasModel, FittedPumasModel}
    @assert(isempty(catmap) || catmap isa NamedTuple)

    legend --> :none

    # extract the provided model
    res = ec.args[1]

    # easy API for use, why bother with nested data structures?
    df = DataFrame(inspect(res))

    # retrieve all covariate names.  Here, it's assumed they're the same for each Subject.
    allcovnames = res.data[1].covariates |> keys

    covnames = isempty(cvs) ? allcovnames : cvs

    # get the index number, to find the relevant `η` (eta)
    covindices = findfirst.((==).(covnames), Ref(allcovnames))

    etanames = [Symbol("ebe_" * string(i)) for i in covindices] # is this always true?

    # create a named tuple
    calculated_iterable = (;zip(covnames,iscategorical.(getindex.(Ref(df), !, covnames)))...)

    # merge the category map, such that it takes priority over the automatically calculated values.
    covtypes = merge(calculated_iterable, catmap)

    # use our good layout function
    layout --> good_layout(length(covindices))

    for (i, covname, etaname) in zip(eachindex(covnames), covnames, etanames)
        covtype = covtypes[covname] ? :categorical : :continuous

        # the reference zero line

        @series begin
            # can tweak this, or allow user to
            seriestype := (covtype == :categorical) ? :boxplot : :scatter
            subplot := i

            title := string(covname)
            ylabel := "η" # do we need this?

            (df[:, covname], df[:, etaname])
        end

        @series begin
            seriestype := :hline
            subplot := i
            color := :black
            linestyle --> :dash

            ([0.0])
        end

        if covtype == :continuous
            @show covname
            @series begin
                seriestype := :loess # defined by DataInterpolations.jl
                label := "LOESS fit" # not used anyway, but in case we decide to include it
                subplot := i

                (df[:, covname], df[:, etaname])
            end
        end
    end

    primary := false

end

################################################################################
#                       Covariate plots versus residuals                       #
################################################################################

@userplot ResPlot

@recipe function f(
            rp::ResPlot;
            cvs = [],
            continuoustype = :scatter,
            discretetype = :boxplot,
            catmap = NamedTuple()
        )

    @show typeof(ec)

    @assert length(rp.args) == 1
    @assert eltype(rp.args) <: Union{PumasModel, FittedPumasModel}
    @assert(isempty(catmap) || catmap isa NamedTuple)

    legend --> :none

    res = ec.args[1]

    df = DataFrame(inspect(res))

    ws = wresiduals(res)

    allcovnames = res.data[1].covariates |> keys

    covnames = isempty(cvs) ? allcovnames : cvs # here, it's assumed covariates are the same for all Subjects.

    covindices = findfirst.((==).(covnames), Ref(allcovnames)) # get the index number, to find the relevant `η` (eta)

    etanames = [Symbol("ebe_" * string(i)) for i in covindices] # is this always true?

    calculated_iterable = (;zip(covnames,iscategorical.(getindex.(Ref(df), !, covnames)))...)

    covtypes = merge(calculated_iterable, catmap)

    layout --> good_layout(length(covindices))

    for (i, covname, etaname) in zip(eachindex(covnames), covnames, etanames)
        @series begin
            seriestype := covtypes[covname] ? :boxplot : :scatter
            subplot := i

            title := string(covname)
            ylabel := "η"

            (df[:, covname], df[:, etaname])
        end
    end

    primary := false

end
